== La vida de Jane Pearson

Por mucho tiempo ha permanecido el peso sobre mi mente,
de dejar una pocas palabras con respecto a los tratos del Señor,
cuando le plació a Él poner Su mano sobre mí en juicio por mis rebeliones;
esperando que sea útil para alguna pobre, sacudida, afligida, tentada y confundida mente.
Porque creo que en mis dolorosos momentos,
habría sido de utilidad para mí haber visto los pasos de otros,
si hubiera tenido la estabilidad para leer o la tranquilidad de mente para ser instruida;
cosa que por un tiempo no tuve, al estar débil y dolorosamente quebrantada,
lamentándome por causa de la intranquilidad de mi corazón.

Nací en Newtown, cerca de Carlisle, de padres sobrios y religiosos.
Al morir mi padre cuando yo era joven,
tuve una mayor experiencia del cuidado religioso de mi madre en nuestra
instrucción. Ella fue dejada con cuatro de nosotros para criar,
y su celo y cuidado por su descendencia no disminuyeron,
por lo que tengo un buen testimonio que dar de su
piadoso cuidado y de su preocupación por nosotros.
Por ese motivo contrató a un maestro de escuela,
para que enseñara a sus hijos en la casa,
y para evitar que fuéramos corrompidos o que aprendiéramos las
inapropiadas costumbres de la gente entre la que vivíamos;
de este modo se nos impidió, más que a muchos de nuestra edad,
que nos asociáramos con los de otras persuasiones.

Le plació al Señor por Su buen Espíritu, obrar en mi corazón en mis años de juventud,
lo que produjo en mí una piadosa tristeza y un temor de que la
muerte me arrebatara mientras aún vivía en mis locuras infantiles.
Cuando la campana fúnebre era tocada por los de otras persuasiones religiosas, ¡oh,
el espanto y temor interior que me acompañaban en esas ocasiones!
Yo decía en mi corazón:
"`Estos ya han sido retirados del escenario de este mundo y establecidos
en la forma en la que deben permanecer para siempre.`"
Mi intranquilidad a veces me dominaba a tal punto,
que yo deseaba saber la edad de los fallecidos y si eran de edades parecidas a la mía;
y si lo eran, se añadían más miedos, los cuales en ese momento eran punzantes.
Pero si estaban más avanzados en la vida,
me esforzaba por apaciguar mis temores al considerarme joven,
y que podría escapar de ser sacada de este mundo en mi juventud;
porque yo tenía miedo a morir,
y el aterrador "`por los siglos de los siglos,`" traía tristeza sobre mí.

Yo amaba leer las Escrituras, especialmente el Nuevo Testamento,
y cuando leía el pasaje donde nuestro bendito Señor es descrito
sufriendo mucho por parte de los orgullosos profesantes de la religión,
quienes lo trataron con desprecio y lo crucificaron, me afligía profundamente.
Yo creía que yo no habría hecho una cosa así,
y por ello mi corazón se conmovía y se enternecía bajo la consciencia de esto.

Por este tiempo le plació al Señor enviar a nuestra región a Mary Kirby,
una ministra de Norfolk, y como estaba sola, me pidió que la acompañara.
Mi madre me dejó, y fue un tiempo en el que coseché algunos beneficios;
porque cuando regresé a casa,
sentí mi corazón en una buena medida limpio y vacío de sus antiguos habitantes.
Mi obstinada voluntad se había sometido significativamente,
y había aprendido a amar el retiro, por lo que me alejada de mis viejos compañeros.

Entonces experimenté un estado de profunda pobreza de espíritu,
lo que hizo que me dirigiera al Todopoderoso de esta manera: "`Señor,
¿qué quieres que haga?`"
En ese momento yo no sabía que había algo en mi conducta que le desagradaba a Él,
pero Su palabra en mí fue: "`No sólo debes dejar de hacer el mal,
sino debes aprender a hacer el bien.`"^
footnote:[Ver Isaías 1:16-17]
Así experimenté, que cuando el espíritu inmundo ha salido,
también nosotros caminamos por parajes secos, buscando reposo sin encontrarlo.
¡Oh, que ese tiempo de sequía y vacío sea pacientemente soportado!
Sin embargo, cuando todos los habitantes son expulsados,
la parte humana es propensa a buscar algo para compensar la pérdida que ha sufrido,
porque ¡cuán difícil es vivir sin buscar la vida en las cosas creadas o externas!
Los sentidos están continuamente buscando algo para sanar esa herida mortal,
y colocar en su lugar algo en la mente vacía; pues es difícil morir así al yo.
Por tanto, muchos tienden a conectarse de nuevo con los que son peores que ellos mismos,
y su postrer estado es peor que el primero.

Siento tal serenidad celestial en mis esfuerzos por reunir estas pocas
observaciones que han permanecido mucho tiempo entre mis papeles,
que no tengo duda de que es correcto que las deje para la posteridad;
al tener en mi corazón una esperanza viva de que la lectura de estos fieles dichos tenderá,
bajo la guía de la Providencia,
a alcanzar y a reducir la naturaleza incircuncisa filistea en algunos.

Las enfermedades que acompañaron a mi familia en mis años de juventud,
me mantuvieron mucho tiempo en casa;
y ahora mi propia debilidad y enfermedades son grandes y muchas.
Sin embargo, mi amor es fiel a la gran y buena causa,
y estaría dispuesta a ir por todo el mundo para edificar al cuerpo,
promover la reforma de la humanidad, y la redención de sus almas por medio de Jesucristo.

Durante un tiempo seguí teniendo un profundo sentido de privación y vacío. Estaba sentada
en nuestra reunión de mujeres para administración de los asuntos de la iglesia en Carlisle,
cuando me pareció claro, que si yo continuaba caminando internamente con Dios,
pronto tendría que hablarles a otros.
La sugerencia de que yo iba a ser llevada por Él
a ministrar a otros estaba tan lejos de humillarme,
que ni siquiera pedí ser eximida,
ni le pedí a mi Maestro divino que tuviera paciencia conmigo;
sino que resueltamente dije: "`Nunca lo haré.`" Así que me aparté como un arco roto,
y creo que entré en la más grande separación de la Vida Divina,
como nunca antes lo había hecho; y habría sido verdaderamente justo,
si la Sabiduría infinita me hubiera cortado en mi desobediencia.
Era culpable de muchas cosas malas,
lo que trajo un pesado juicio sobre mí. En esa época
estaba viviendo con una tía en Carlisle,
y estaba muy expuesta al mundo, pues ella tenía una tienda,
y yo estaba fuera de la estricta mirada de mi madre.

Tenía entonces unos diecisiete o dieciocho años.
A lo largo de todas las etapas de mi vida,
yo había sentido un gran amor por los buenos Amigos,
y ellos a menudo habían manifestado amor por mí,
reconociendo la parte valiosa en mí y pasando por alto la que era reprensible,
confiando (no tengo duda) en que el Señor continuaría Su propia obra.
Y la actitud abierta de ellos hacia mí, estaba tan lejos de engendrar desestima en mí,
o de inducirme a considerarlos faltos de discernimiento,
que esta tuvo un efecto sobre la mejor parte de mí; porque yo en verdad,
habría podido lavar los pies de los santos.
Los Amigos ministrantes se alojaban en la casa de mi madre,
y algunas veces recibí la bendición, la cual está fresca en mí hasta el día de hoy.

Entre los veintiuno y veintidós años, me casé con John Pearson,
un joven sobrio y religioso.
Alrededor de un año después de mi matrimonio, mi falso descanso se quebró;
aunque confío que estaba casada correctamente y en
la sabiduría del Señor. Unida a un esposo escogido,
nadaba como en un océano de placer, pero en lugar de paz en la tierra,
experimenté una espada que atravesó mi corazón. Mi desesperada
condición estaba presente en mí día y noche,
siempre que estaba despierta.
En realidad, yo dormía poco.
El sueño se alejaba de mis ojos y el dormir de mis párpados;
de modo que cuando llegaba la noche, yo deseaba la mañana.
Y aunque había sido preservada de graves males,
la mano del Señor era tan pesada en juicio contra la parte pecaminosa e impura en mí,
que había suficiente trabajo para Su traspasadora espada en mi corazón,
la cual divide entre lo precioso y lo vil,
entre lo que Le sirve a Él y lo que no Le sirve.

En mi opinión, mi caso era entonces sumamente deplorable;
de modo que no comía ni dormía mucho, lo que ocasionó un visible deterioro de mi salud.
De hecho, yo era una maravilla para la vista;
la gente se preguntaba qué me había sucedido.
El enemigo me seguía de cerca con los más graves asedios;
cosas que mi alma aborrecía me las cargaba como propias.
Y yo, al no tener fuerza para resistirlo con un "`apártate de mí,
Satanás;`" o por otro lado,
al no tener experiencia para distinguir entre lo
que procedía del enemigo y de sus gravosas insinuaciones,
y lo que se levantaba de la debilidad de mi naturaleza,
todo en mí parecía fuera de orden y como una masa confusa.
Yo verdaderamente creía que nadie había estado en un estado así antes,
ni tampoco había leído de ningún Amigo que hubiera pasado por semejante tiempo de prueba,
el cual duró, si se puede creer, _catorce años,_
durante los cuales temí que nunca llegaría al otro lado.

Comía mi pan llorando y mezclaba mi bebida con mis lágrimas.
Era como estar entre serpientes ardientes y en las fauces de un enemigo devorador,
quien se regocijaba sobre mí insinuando que la siguiente tentación me arrastraría,
y disparando cosas en mi mente una tras otra,
tan rápidas como un pensamiento y tan oscuras como la noche más oscura.
Ojalá mis dificultades "`fuesen esculpidas con cincel
de hierro y con plomo en piedra para siempre,`"^
footnote:[Job 19:24]
porque ciertamente, ellas están más allá de mi poder de descripción;
y si no se hubiera extendido la misericordia sobre mí en esa época de prueba,
realmente habría caído. La época era tan severa, que no podía ver cómo vivir bajo ella,
y deseaba que el Todopoderoso, mediante un acto de Su poder,
me arrebatara de entre los mortales, aunque fuera por una muerte accidental;
porque yo todavía creía que si Él me tomaba, sería en misericordia.
Tan ferviente era yo en pos de la santidad y virtud,
que a menudo le rogaba a Dios que no me permitiera pecar contra Él,
para no estar eternamente posicionada con los espíritus inmundos y abominables,
que mi alma aborrecía.

Entonces me aborrecía en polvo y cenizas,
porque se le había permitido al enemigo asaltarme.
Pero a través de todo, mi mente fue preservada clara y mi razón sana.

Durante ese tiempo me sentía muy atraída hacia el interior en oración,
porque mi estado de tentación y desconcierto verdaderamente lo requería;
y creo que por un tiempo oré sin cesar.
Y sin embargo, el Señor sabía lo que yo necesitaba,
a fin de capacitarme para Su obra y servicio.
Por lo tanto, para mi mayor refinamiento, le permitió al enemigo que se acercara aún más;
aunque yo habría podido decir con uno de antaño: "`¿Por qué, pues, inculpa?
Porque, ¿quién ha resistido a su voluntad?`"^
footnote:[Romanos 9:19]

La siguiente es una de las más angustiantes pruebas con la que jamás me haya encontrado.
Una noche, que el enemigo me acusó de mal,
y yo me volví en oración al Juez de toda la tierra,
apelando a que Él sabía que yo no era malvada,
y rogándole que reprendiera al devorador por mi bien,
y me hiciera libre para servirle a Él--fue lanzado en mi mente tan rápido como un rayo:
"`¡No hay Dios!`" ¡Oh, cómo lloré entonces,
creyendo que nunca había habido un hombre o una mujer con el menor vestigio de bien,
que hubiera sido probado de esta manera!
Entonces pensé que había pecado contra el Espíritu Santo,
y que yo era la más miserable criatura sobre la tierra.
Y el enemigo siguió firme con su amargo susurro, diciendo: "`¿A qué le oras?
¡No hay Dios!`"

Nunca le revelé a nadie mi condición bajo este doloroso tiempo;
porque creía que a quienquiera que le expusiera mi mente,
supondría que yo era culpable de alguna cosa horrenda, y que por eso era rechazada.
Y creía que si me topaba con el desánimo de ellos,
no podría soportar la mano de Dios en juicio, porque había pecado contra Él. Pero al fin,
experimenté la verdad de esta declaración:
"`Porque luego que hay juicios tuyos en la tierra,
los moradores del mundo aprenden justicia;`"^
footnote:[Isaías 26:9]
pues llegué a experimentar verdaderamente,
la pureza interna del corazón y limpieza de las manos.
Y a Su tiempo, el Señor me dio acceso a Su trono,
y el Espíritu de oración y súplica fue derramado sobre mí,
junto con un "`ciertamente hay Dios que juzga en la tierra.`"^
footnote:[Salmo 58:11]
Y luego experimenté una consciencia santa de esta verdad,
"`El Señor vive,`" y "`porque Él vive, yo también vivo.`"^
footnote:[Juan 14:19]

Cuando este tiempo de prueba había preparado el camino del Señor y enderezado Sus sendas,
entonces pasó, y yo pude decir: "`El Señor vive, y no hablo falsedad,
porque sé lo que me ha costado el precioso conocimiento de Dios.`"
Hago notar estas cosas para la ayuda de cualquiera que sea probado como lo fui yo;
porque si yo me hubiera topado con un relato similar me habría sido de alivio.
Es posible que haya testimonios de Amigos en los relatos de sus vidas,
que sean de algún modo parecidos, pero yo no los había leído, o si los había leído,
habían desaparecido de mi mente.
Tampoco podía creer que a alguien que estuviera bajo la atención divina,
o la disciplina de la Mano santa,
se le permitiera permanecer tanto tiempo bajo sugerencias tan oscuras y agobiantes.

¡Ojalá que todo aquel que sea probado de manera similar,
crea que se le abrirá un camino para su escape! ¡No se desanimen ni pierdan su confianza!
Me siento unida a la semilla sufriente dondequiera que se encuentre,
o de cualquier sociedad que sea.
Lloro con los que lloran, sintiendo compasión por sus angustias.
Mi piedad y tierno sentimiento es para estos,
y me dirijo a ellos (no a partir de algún grado de experiencia del que pueda jactarme,
sino desde la profundidad de la humillación) diciendo: "`¡Confíen en Dios.
Él puede poner a Su semilla en libertad y lo hará!`"

Entonces comencé a tener grandes escrúpulos con respecto a mi vestimenta,
la de mis hijos, y los muebles de nuestra casa,
y anhelaba tener todo en sencillez y sobriedad.
Pensé en que Juan había vestido de pelo de camello,
que llevaba un cinto de cuero alrededor de sus lomos,
y que su comida había sido langostas y miel silvestre.
Que ahí no había habido ninguna delicadeza, ni en el comer ni en el vestir.
Todo lo que la fuerte voluntad en mí parecía aborrecer, o tener una aversión,
a eso mismo era conducida bajo la cruz;
aunque pareciera indigno para mi propio carácter y disposición,
que no estaban totalmente redimidos de la pompa y
del deseo de ser algo ante los ojos de mundo.
Fui guiada de esta manera,
hasta que mi voluntad fue sometida y fui suficientemente sencilla,
al ser afligida en todo momento; porque yo siempre tenía algún escrúpulo en mi mente,
sobre si las cosas eran correctas o no, hasta que me volví flexible y dócil,
lista a tomar cualquier impresión que el Señor quisiera estampar en mí. ¡Oh,
cuánto oro que sea un sello de santidad, durante mi estancia en la mutabilidad;
y después, que pueda unirme a la iglesia triunfante,
alabando al Señor Dios y al Cordero por los siglos de los siglos!

Por este tiempo empecé a experimentar algo de luz y vida a mi alrededor.
Yo no habría podido imaginar que sería tan libre de los susurros
e insinuaciones amargas de la punzante y torcida serpiente;
porque es natural concluir, cuando las cosas están tan fuera de orden,
y el adversario ha efectuado tal incursión en la mente, haciendo presa de ella,
que sería difícil arreglar las cosas.
Pero es la obra del Señor, y Él recibirá la alabanza,
porque todo se debe a Él y nada se debe a la criatura.

Experimenté un significativo dominio y obtuve un poco de victoria;
porque sentí que la cabeza de la serpiente había sido herida, el acusador derribado,
sus acusaciones silenciadas,
y yo absuelta de sus falsos cargos contra mí. Y en lugar de esto,
obtuve un precioso sentimiento de justificación--en el que las
cosas viejas habían sido eliminadas por el bautismo que salva,
todas las cosas habían sido hechas nuevas, y todas las cosas eran de Dios.
Entonces empecé a tener de nuevo la idea,
de que debía de contarles a otros lo que el Señor había hecho por mi alma,
cómo me había sacado del pozo de la desesperación, del lodo cenagoso,
y me había hecho sentir el fundamento seguro.
Vi que debía mantenerme sobre ese cimiento y proclamar
la nueva canción que Él había puesto en mi boca.

Ese fue un día de duro trato;
porque fui puesta a prueba para ver si mantendría el pacto que había hecho
con el Señor en los días de mi profunda angustia--que consistía,
en que si Él me libraba del enemigo, me ordenara lo que le placiera y yo obedecería;
fuera lo que fuera.
En las asambleas del pueblo del Señor (y era un privilegio
para mí estar entre un pueblo espiritualmente vivo),
nuestras reuniones a menudo eran favorecidas con testimonios vivos.
En tales ocasiones,
frases de las Escrituras impresionaban mi mente a veces con algún grado de vida y poder,
y en concordancia con mi estado infantil e inexperiencia,
sentía cierta preocupación de declararlas a la audiencia,
pues la evidencia no era tan completa ni tan clara
como mi tímida mente requería y realmente necesitaba;
porque yo deseaba ser preservada de decir: "`Así ha dicho Jehová,
cuando Jehová no había hablado.`"^
footnote:[Ezequiel 22:28]

Esto provocó un fuerte conflicto, la prueba del vellón mojado y seco,
pues mi natural timidez estaba estrechamente unida al correspondiente
cuidado de no ofrecer el fruto prematuro que pronto decae.
Esto me hizo muy cautelosa y precavida,
pues creía que muchos habían confundido la preparación
para este oficio con la comisión misma,
y por tanto, habían sido enanos en el ministerio.
Por otro lado,
el recuerdo del pacto que había hecho con el Señor en los
días de mi dolorosa esclavitud y profunda cautividad,
y el hecho de que no estaba respondiendo a Sus requerimientos,
hizo de este un tiempo de gran aflicción para mí. En las reuniones,
el asunto se levantaba y se esparcía en mi mente hacia la gente, y sin embargo,
no sentía el mandato de hablar.
¡Oh, si alguno de ustedes se encuentra probado de igual manera,
si está rendido con una mente dedicada al Señor, a este le diría: "`No temas,
vendrá el tiempo cuando no dudarás con respecto a la voluntad del Señor!`"

Estuve unos nueve meses bajo este tiempo de prueba.
Esto desgastó la fuerza de mi cuerpo; mis rodillas estaban débiles, mi carne fallaba,
aunque no por abstenerme de comer.
Mi rostro estaba a menudo afligido por mucho llanto
en esta época de aventamiento y zarandeo,
y cubrían mis párpados densa oscuridad.^
footnote:[Job 16:16 LBLA]
Sin embargo, y pesar de todo, yo tenía una pequeña esperanza,
que como un ancla sostenía mi alma.
Y se levantó la creencia de que Aquel que era mi confianza,
en Su propio tiempo desplegaría los misterios de Su reino y daría una evidencia indiscutible,
con inmaculada claridad,
de que era Su voluntad que la candela que Él había encendido fuera puesta en el candelero,
y diera luz a los de alrededor.

Gracias a Su nombre para siempre digno,
Él lo cumplió. Porque cuando llegó el momento correcto,
en el que yo debía abrir mi boca en una reunión pública,
no tuve duda de que era Su mente y voluntad.
Pero aun así, por miedo, lo razoné tanto que el impulso desapareció,
pero no fui severamente castigada por ello,
ya que mi corazón estaba firmemente inclinado a servirle
a Él. La voluntad de hacer el bien estaba presente,
pero me sentía débil en la realización de ella;
así que el Señor me perdonó y mi mente disfrutó el bien hasta el siguiente día
de reunión. Entonces fui con mucho temor a nuestra pequeña reunión en Graysouthen.
Unas pocas palabras se presentaron vívidamente en mi mente, que pronuncié con mucho temor.
Recuerdo bien el tema;
la esencia del cual era que si nos volvíamos internamente más al Señor en nuestras reuniones,
ellas serían más favorecidas de lo que a menudo encontrábamos que eran.
Y, ¿no es esto una verdad en la actualidad?

El haber sido cautelosamente guiada al principio,
ha sido útil para mí durante el resto de mi vida en lo que se refiere al ministerio,
para mi vigilancia contra las falsas opiniones y presentaciones en mi mente,
o para no confundir la parte imaginaria con la voluntad revelada de Dios.
¡Oh, la paz que sentí esa noche después del corto testimonio!
Habría sido aceptable entonces, "`partir y estar con Cristo,
lo cual es muchísimo mejor.`"^
footnote:[Filipenses 1:23]

Ahora tenía una gran paz de espíritu,
de modo que mi corazón en lugar de ser un lugar de chacales, lechuzas y búhos chillones,
de pelícanos y erizos, empezó a haber en él una melodía, por así decirlo,
la voz del Hijo de Dios, cuyo rostro es hermoso.
Y entonces, el árbol de arrayán,
boj y pino brotaron en el corazón que antes había sido un criadero de ortigas.
Este es el cambio que es producido en el hombre al nacer
de nuevo de la Semilla incorruptible y Palabra de Dios.
Este era el cambio que fue obrado en mí.

Yo entonces hablaba frecuentemente en las reuniones, y tenía satisfacción haciéndolo,
y los Amigos no me desanimaban en mis pequeños movimientos infantiles,
sino que los aprobaban, aunque con un cuidado piadoso.
Y por la abundante misericordia del Señor, me movía en mi don con sencillez,
y no escogía por mí misma de qué hablar, ni iba tras revelaciones,
ni adornaba mis comunicaciones en conformidad con la voluntad de la criatura,
ni tampoco me atrevía a contener mis revelaciones--todo lo cual es desagradable.
El Señor me enseñó a dejarlo ir tal como había llegado.

Como yo tenía un gran amor y cuidado por la bendita causa del Señor,
para que no sufriera por los débiles defensores que la promulgaban,
siempre pensé humildemente de mí misma.
A veces, por retener algo de lo que se me había dado para ofrecer,
me convertía en autora de confusión y desorden,
y por eso las personas no eran tan edificadas, ni yo tan consolada,
como se podría esperar del conflicto que yo había padecido.
Creo que este error tenía algún fundamento en mi deseo de
esperar hasta tener "`la forma de las sanas palabras`"^
footnote:[2 Timoteo 1:13]
que nadie pudiera condenar.
Porque aunque yo no buscaba revelaciones divinas, ni las adornaba según me placía,
aun así, todos deben tener un modo de expresarse adecuado al asunto,
a fin de transmitirle a la audiencia sus sentimientos sobre las cosas religiosas.
Basada en esto,
yo a veces deseaba tener mi pequeña ofrenda bien ordenada en mi mente antes de hablar,
porque temía ser culpada de citar o de aplicar mal las Sagradas Escrituras.
Sin embargo, fui conducida a ver claramente,
que los ministros de Cristo deben levantarse cuando tal vez,
sólo se les haya dado una palabra,
y deben ministrar según la habilidad con la que son favorecidos,
no temiendo en absoluto al hombre,
"`cuyo aliento está en su nariz,`" sino sirviendo y temiendo únicamente al Señor.

Entonces, cuando las pruebas internas disminuyeron,
empecé a tener grandes pruebas externas.
Estaba casada con un esposo afectuoso,
quien soportó parte de mis sufrimientos en mi infancia espiritual.
Tenía siete hermosos hijos,
cuatro niñas y los más pequeños eran tres niños. Hasta ese momento el
Señor había puesto un cerco alrededor nuestro y de todo lo que teníamos.
Aunque nosotros al principio no teníamos mucho en el mundo,
crecimos rápidamente en las cosas temporales.
Le plació al Señor quitar a dos de los más pequeños por la viruela.
Me afligió mucho que se nos hubiera abierto una brecha; en realidad,
me dejé llevar por la angustia.
Entonces se proclamó en mi oído interior un lenguaje que decía,
que si yo no dejaba de afligirme desmesuradamente, tendría más dificultades.
La parte afectuosa era fuerte, sin embargo,
confío en que no murmuré contra estas asignaciones de la infalible Sabiduría.

¡El año siguiente me fue quitado mi amado esposo!
Oh, yo habría podido separarme de todos mis hijos con tal de haberlo tenido a él;
porque estaba tan unida a él, que creía que si él moría, yo no podría vivir.
Él había sido mi fuerza externa, y me había apoyado en él para todo lo de este mundo.
Estoy inclinada a dar testimonio de su valor,
como el de la pequeña ofrenda de la viuda a sus hijos, o a los hijos de los hijos,
para que cuando nos hayamos ido ellos puedan ver de qué tipo de estirpe han surgido.
Por el bienestar de estos, mi propia alma se conmueve en mi interior,
y me hace ir inclinada implorando,
que el auxilio divino sea la ayuda de ellos a través de este valle de lágrimas.

[.embedded-content-document.testimony]
--

[.blurb]
=== Testimonio de Jane Pearson sobre su fallecido y amado esposo, John Pearson, quien partió de esta vida el 14 del mes Seis de 1774.

Nació de padres creyentes, quienes le dieron una educación aceptable, y creo,
que según lo mejor de sus posibilidades,
lo criaron en la disciplina del Señor. Tuvo una inclinación religiosa desde su juventud,
de modo que en cierto sentido, fue un Nazareno desde su nacimiento,
demostrando plenamente que buscaba una patria celestial.
Durante el tiempo que estuvo en este mundo pasó por varias luchas,
pues estuvo más expuesto a él que muchos otros,
ya que su negocio era la fabricación de lino.
A pesar de eso, se condujo con honor en todos sus compromisos,
y ganó una buena subsistencia para su familia; y puedo decir sin ninguna duda,
que mantuvo su vida espiritual a través de todo.

Era un hombre de vida y conducta inocentes, y de carácter manso,
más dispuesto a recibir un trato áspero que a darlo,
y a sufrir el agravio que a resentirse por una ofensa.
Era moderado incluso hasta la abstinencia.
En su relación como esposo, era irreprochable.
Cuando recuerdo su ternura hacia mí y su familia, no puedo sino lamentarme; sin embargo,
creo que ha sido llevado a un remanso de descanso,
porque era evidente que la tumba no tendría victoria en su partida.
Su enfermedad fue tediosa,
pero estaba rendido a que la vida o la muerte fuera
su porción. Con frecuencia decía que anhelaba irse,
y que apenas creía posible que estuviera tan dispuesto a dejarnos.

El día anterior a su muerte llegó a verlo un Amigo y tuvo oportunidad de estar con él,
el cual fue un tiempo grato.
El Amigo le dijo que él todavía podía mejorar un poco, pero le respondió:
"`Prefiero irme; he sentido los dolores de la muerte.
¡Déjame ir!`"
Parecía que estaba reconciliado con la tumba, y le dije: "`¿Entonces, querido,
debes estar convencido de que tu cambio será para bien?`"
Él respondió: "`Sí, así lo creo;`" hablando con humildad admirable.
El día antes de morir,
se tomó el pulso tres veces para saber qué tan cerca estaba su cambio,
y le preguntó al doctor cuánto tiempo le quedaba.
Yo quería que él no hiciera esa pregunta, y como un manso cordero, no la repitió.

Estoy convencida de que él sentía la seguridad de ser aceptado por el Todopoderoso,
la cual fue manifiesta por la fuerza y serenidad celestiales
que lo acompañaron hasta sus últimos momentos.
Su madre, que era una persona de edad avanzada y estaba muy enferma,
al ser traída para que se despidiera,
él de manera profética le dijo que él debía irse primero,
pero que ella lo seguiría pronto.
Y así sucedió, pues mientras él expiraba,
ella empezó a mostrar síntomas de su partida y lo siguió unas dos horas después;
de modo que terminaron su camino casi juntos.

¡Oh, mi pérdida es inexpresable!
Su bondad, su cercanía a mí en el sentido religioso, no se pueden describir.
Yo había pasado por varias y profundas pruebas;
muchos fatigosos años habían pasado sobre mi cabeza
mientras estaba bajo la preparadora mano de mi Dios.
Pero su compasión, su paciencia conmigo,
su benevolencia hacia mi debilidad en mi estado infantil, no pueden ser escritas.
Su recuerdo es bendito,
y sus excelentes virtudes ascienden al Padre de los espíritus
y se asemejan a las oraciones y limosnas de Cornelio,
tenidas en eterna memoria.

Me he esforzado por no dejarme llevar por el sentimiento
a la hora de dar este breve relato,
y sólo he contado lo que creo que el espíritu en mí testifica de la verdad;
tampoco me sentía tranquila sin hacerlo.
Él partió sin ninguna lucha, como quien cae en el más dulce de los sueños,
y fue dignamente sepultado en el cementerio de los Amigos en Graysouthen,
a la edad de cuarenta y nueve años.

[.signed-section-signature]
Jane Pearson.

--

El Señor estaba ahora, a punto de despojarme de mis seres queridos.
El año siguiente se llevó a mi hijo mayor con fiebre,
de modo que me quedé sin hijo varón. También me manifestó que Él
requería de mí que viajara un poco al servicio de la Verdad.
Me rendí y mis amigos me favorecieron con un certificado.^
footnote:[Los ministros de la Sociedad de Amigos siempre
viajaban con un certificado escrito de respaldo y unidad,
preparado por los ancianos de la reunión a la que pertenecían.]
Emprendí mi viaje con mi honorable amiga Hannah Harris.
La acompañé por Lancashire,
y luego mi querida amiga Barbara Drewry se reunió conmigo en Settle.
Visitamos todo Yorkshire, excepto la Reunión Mensual de Richmond.
Entonces, al sentir una fuerte inclinación de regresar a casa,
lo hice y encontré a mi familia bien, excepto a mi querida madre que vivía conmigo.
Ella estaba un poco decaída, aunque no tanto como para que se notara.
Pero en unas dos o tres semanas cayó enferma y murió. Menciono esto para
que los Amigos presten atención a sus sentimientos y persuasiones,
con respecto al momento de regresar al hogar,
porque si ella hubiera partido en mi ausencia,
habría corrido el peligro de dejar entrar al razonador.
¡Oh, la bondad de Dios quien prolongó su vida hasta mi regreso!

Fui dejada entonces con mi suegro, quien era un hombre inestimable, y mis cuatro hijas.
La segunda más joven, una amable joven de casi diecinueve años,
después de estar un tiempo en el extranjero, perdió su salud.
Continuó en un estado de gran debilidad casi tres años, y partió de esta vida en 1784,
después de la muerte de mi suegro que había sucedido un poco antes de la de ella.

Quedé con tres hijas.
La familia que una vez estuvo llena de personas, ahora se sentía solitaria;
pero el Señor ha sido extremadamente bondadoso conmigo.
Cuando me lamentaba por la pérdida de mis allegados, especialmente la de mi esposo,
la amable Bondad misericordiosamente argumentaba de la siguiente manera:
"`¿Qué te he hecho?
He llevado a tus seres queridos a una mansión de descanso, los llamé a una vida mejor.
Y quitaré, según Mi beneplácito, al resto de tu familia; y luego se reunirán,
para no separarse nunca más.`" En ese momento tenía una esperanza, sí, una preciosa fe,
de que el Señor misericordiosamente me preservaría a mí
y a los míos hasta el fin en una medida de inocencia.

Debo reconocer,
que yo había permitido que prevaleciera en mi mente la fuerte persuasión
de que el Señor había alejado a mi esposo de mí por disgusto,
porque yo no me había desempeñado fielmente en el ministerio,
o porque algo más andaba mal en mí. Incluso fui tan
débil como para requerir de Él una señal,
aunque Él antes me había convencido plenamente de que no
había sido por disgusto hacia ninguno de nosotros.
¡Oh, ese fue un tiempo de gran abatimiento!
En aquel momento le pedí, que hiciera que alguno de Sus siervos,
con quien yo nunca había tenido correspondencia, me escribiera,
y que yo lo tomaría como una señal. Él había corregido en Su misericordia,
y ahora Se dejaba suplicar; porque esa inestimable Amiga, Mabel Wigham,
me dirigió una carta con tierna simpatía,
comunicando sus sentimientos de que mi esposo había sido quitado en misericordia,
y que mi hijos y yo seríamos preservados.
Hago notar esto, para que los Amigos sean fieles en todos los aspectos,
porque eso me hizo mucho bien.

Entonces tenía la inquietud en mi mente (y creo que había estado delante
de mí por algunos años) de visitar las reuniones de los Amigos en la parte
oeste de esta nación. Cornwall me constreñía mucho,
de modo que si hubiera tenido alas, habría volado hasta allí para aliviarme.
Se lo informé a algunos de mis amigos,
y ellos me animaron y se unieron conmigo en mi expectativa.
Luego, lo di a conocer en la Reunión Mensual y obtuve su certificado,
y tuve a mi querida amiga, M. Haworth, de Haslingden, por compañera.
Visitamos la mayoría de las reuniones en Lancashire, Cheshire, Shropshire,
Worcestershire, Somersetshire, Devonshire y Cornwall.
El Señor obró poderosamente en mí para con los afligidos,
porque yo había atravesado mucha aflicción, y por ello me había vuelto muy sensible,
captando fácilmente un sentimiento de dolor dondequiera que lo encontrara.
Me perdí varias reuniones en mi regreso a casa, porque estaba mal de salud,
y creía que era seguro y legítimo regresar.
Encontré a mi familia bien, y tuve la evidencia de paz como respuesta a mi obediencia.

Había llegado entonces a los cincuenta y seis años,
y todavía me acompañaban las aflicciones.
Al morir mi segunda hija, sólo me quedaron dos.
Ella fue una joven inocente y virtuosa,
que había soportado una larga enfermedad con paciencia y resignación,
y creo que fue recogida en su reposo en misericordia.

En 1791 me trasladé a vivir a Whitehaven, antes de la muerte de mi hija menor;
a cuyo matrimonio con un Amigo que pertenecía a esa reunión yo había consentido.
Nuestro traslado ahí fue también en gran medida, idea de mis dos hijas.
La hija que todavía vivía conmigo estaba deseosa de vivir ahí,
para serle útil a su hermana casada, cuya familia estaba aumentando.
¡Pero, oh, las dolorosas pruebas que atravesé en esta reunión! Realmente me desgastaron,
junto con otras circunstancias difíciles que me ocurrieron en ese lugar.
En efecto,
muchas copas amargas tuvimos que beber mis pobres niñas
y yo ahí. Pero si contribuyeron con nuestro refinamiento,
entonces está bien; porque nuestros cuerpos en verdad se debilitaron por ello.
Hice lo mejor que pude bajo las pesadas pruebas que enfrenté.
El Señor sabe que mis oraciones eran casi incesantes,
bajo el peso de cosas desagradables.

Mi hija menor era una joven religiosa y piadosa, y murió el año que nos trasladamos.
Ella era muy delicada, de carácter manso y espíritu tierno; y sin embargo,
había atravesado dificultades, de modo que en sus últimos momentos expresó,
que ríos de lágrimas habían corrido por sus mejillas, y que si moría (lo cual no temía),
entonces moría inocente, porque nunca le había hecho mal a nadie.
A menudo decía alentadoramente: "`El Señor sabe qué es lo mejor para nosotros.`"
Ella tenía una fuerte aprehensión de que debía morir,
pero yo creía que todo estaría bien,
por la dulce perspectiva de bien que había tenido con respecto a ella,
mientras estaba en una reunión un poco antes de este tiempo.
A partir de ese descubrimiento, me aferré a la esperanza de que ella se recuperaría,
a lo que ella comentó durante su enfermedad: "`Madre, te has equivocado.`"
Yo respondí: "`Querida, yo vi algo muy consolador acerca de ti,
y pensé que todo estaría bien.`"
Ella respondió: "`Todo _estará_ bien,`" y añadió,
"`he pensado a menudo en aquel Amigo de Manchester,
quien durante una reunión familiar señaló,
que a algunos de los presentes no les quedaba mucho tiempo.
Pero el estado del que él habló me pareció demasiado bueno,
como para aceptarlo para mí. Y yo lo apliqué a otro
del grupo que en ese momento estaba indispuesto.`"
Mi hija dejó tres niños bajo el cargo de los parientes sobrevivientes.

Aunque a menudo mi porción es sentarme en silencio
en las reuniones del lugar donde resido ahora,
aun así tengo preciosas revelaciones y divinas insinuaciones en mi regreso a casa,
incluso con respecto a individuos.
Pero la dureza de corazón se ha deslizado en las mentes de algunos,
y puede que sea correcto dejarlos en paz.

2 del mes Seis, 1793.
No sé por qué estoy retenida en este lugar,
excepto para sufrir fielmente con la semilla sufriente aquí. He sentido nuevamente,
una preciosa unión con nuestro amado Señor en Su estado
crucificado en los corazones de los profesantes del Cristianismo.
¡Oh, los bautismos que he experimentado en nuestras reuniones!
Ha entrado un espíritu activo que toma su comida en la superficie,
o la atrapa volando en las regiones aéreas.
Algunos buscan alimentarse y ser alimentados con comida de esta naturaleza.
Me he sentado dolorosamente bajo ciertos testimonios recientes,
cuando me parecía claro que el pecado todavía tenía su imperio en el orador,
y que eso que se entregaba, aunque sólidas verdades, no mataban al hombre de pecado.
No me refiero a nadie que pertenezca a nuestra reunión;
hay una preciosa semilla en este lugar, con la que puedo unirme en gran medida.

1 del mes Quinto, 1794.
Hoy estuve en una reunión pesada.
Sentí que densas nubes se acumulaban, que el sol y la luna se oscurecían,
que las luces mayores y menores se retiraban.
En mi labor interna, profundamente ardua, no veía luz en el horizonte,
y estaba muy segura de que la amargura de la muerte estaba alrededor.
Luché en silencio, hasta que mi misericordioso Maestro me hizo ver, que donde Él estaba,
ahí debía estar también Su siervo.
Recibí cierto consuelo de eso,
al descansar en la creencia de que yo era de la Semilla sufriente,
aunque el miembro más pequeño del cuerpo, o el más bajo de la casa del Padre.
Creo que en esa reunión tuve una gran variedad de sentimientos,
y que tal vez haya experimentado los extremos de la felicidad y de la desdicha.
En un momento de silencio, una palabra confirmadora fue pronunciada internamente,
y aunque pobre gusano, tenía esperanzas de que se aplicara a mí. Fue la siguiente:
"`Mi presencia irá contigo y te daré descanso,`" bajo la cual,
estaba lista a cantar el cántico de Moisés, el siervo del Señor,
y el cántico del Cordero.
En otro momento, mi mente estaba tan eclipsada por el poder de la Verdad,
que el tiempo era demasiado solemne como para que se oyera alguna voz,
y la nube y la gloria eran tan grandes que nadie podía ministrar.

Mes Seis, 1794.
He regresado de Broughton,
donde he permanecido por nueve semanas por causa
del débil estado de salud de mi única hija viva.
Me sentí cómoda mientras estuve allá,
y con un gran ensanchamiento de corazón hacia los
pocos Amigos que pertenecen a ese lugar.
¡Ojalá sean beneficiados!
En verdad se les entregó misericordia gratuitamente,
y no por obras de justicia que hayan hecho,
porque los considero deficientes en el gran deber de asistir a las reuniones religiosas.
¡Cuán lamentable es, cuando los ancianos y obispos se quedan en la casa con su bagaje,^
footnote:[Una referencia a 1 Samuel 25:13]
mientras otros se esfuerzan intensamente por promover la Verdad!

Mes Ocho, 1794, Whitehaven.
Hoy nuestra Reunión Mensual ha sido un tiempo muy propicio
para mí. Mi alma se levantó por encima de sus dificultades,
bajo un precioso sentido de que en mi travesía por la vida hasta ahora,
el Señor me había mirado siempre para bien y vigilado mis pasos.
Y aunque no puedo
decir que nunca haya dado pasos en falso,
Aquel que conoce mi corazón sabe que la causa es mi debilidad.
¡Oh, cuán débil somos cuando nos despojamos de Su ayuda salvadora!
Sin embargo, Él ha perdonado todo en completa misericordia, y me ha dado amablemente,
una primicia de las alegrías de Su reino--una sensación
en la que no hay sentimiento de tristeza,
ni más suspiro, ni lloro, sino un gozo sin mezcla.
En esta condición he estado lista a pensar que los
días de mi aflicción están cerca de su fin,
al tener un fuerte "`deseo de partir y estar con Cristo,`"^
footnote:[Filipenses 1:23]
y sentir sometidos a todos los enemigos de mi alma,
de modo que pude orar por los que han abusado rencorosamente de mí. Es bueno para nosotros
que permanezcamos en este lugar celestial en Cristo Jesús. Hoy estuve en silencio;
la plenitud de la gloria era demasiado grande como para ministrar.

22, 1794.
He estado en una reunión. ¡Oh,
el zarandeo que experimento con respecto al ministerio con el que estoy dotada!
Aunque pienso que fui verdaderamente llamada, que entré en el momento adecuado,
y que me he movido con piadoso temor en él, no escogiendo mi propia manera,
ni obrando para mí misma,
aun así me siento tan baja como para creer que nunca he sido útil.
Hoy abrí la boca, según pensé,
por un pequeño impulso o movimiento de instrucción profética para,
a partir de mi pequeña medida de harina, cocerle a Él un poco de pan primero.^
footnote:[Ver 1 Reyes 17:10-15]
En esto no hay ningún exceso,
sino únicamente un grano de fe en el que sería suministrada Su provisión,
respondiendo a mi necesidad.
Aventuré mi ofrenda en verdadera sencillez, hasta donde sé. Pero, ¡oh!,
la bofetada del enemigo que recibí al regresar a casa fue verdaderamente amarga.

Estoy cerca de los sesenta años, y la fuerza de mi cuerpo está muy disminuida.
Me he debilitado mucho,
y no espero que pase mucho tiempo antes de que me encierren
los estrechos confines de la silenciosa tumba.
¡Oh, qué feliz momento cuando sea liberada de la vista y voz del opresor!
Porque aunque algunos sepan que yo he sufrido cosas difíciles,
ninguno ha conocido la angustia de mi corazón. Está más allá de toda descripción,
pero es conocida por Dios.
A menudo he tenido que recordar al santo Job,
y citarlo en el ejercicio de mi don en la honesta labor entre la gente, y decir:
"`Hoy también hablaré con amargura; porque es más grave mi llaga que mi gemido;`"^
footnote:[Job 23:2]
y así ha sido la mía, incluso en este período tardío de mi vida.
Él también declara: "`He aquí, yo clamaré agravio, y no seré oído; daré voces,
y no habrá juicio.`"^
footnote:[Job 19:7]

Hoy he intentado llegar a la conclusión (como lo he hecho en otras ocasiones anteriores),
de que no predicaría más en este lugar, porque la fuente del Evangelio está muy tapada.
Encuentro que "`si hablo, mi dolor no cesa; y si dejo de hablar, no se aparta de mí.`"^
footnote:[Job 16:6]
Pues he intentado de reunión en reunión,
lo que el silencio haría por mí. Me examino a mí misma,
buscando la razón por la que no me siento animada
en mi ministerio como en los días de mi juventud.
Realmente llego a la conclusión de que no hay vida en mí,
de modo que ahora deseo con toda vehemencia el alojamiento de un caminante en el desierto,
donde pueda alejarme de mi pueblo y dejarlos.
Me siento cansada de estos tiempos de sufrimiento.
Son más de lo que mi cuerpo puede soportar.

8 del mes Cuatro, 1795.
Estuve en nuestra reunión entre semana, en la que vi que "`nacemos para la aflicción,
como las chispas que se levantan para volar por el aire.`"^
footnote:[Job 5:7]
Vi que la mente humana es por temporadas como una esponja,
que absorbe las aflicciones hasta que se hunde en aguas profundas; sí,
ellas fluyen en el alma.
¡Oh, las perplejidades que experimentamos en este corto espacio de tiempo!
Pocos y malos han sido nuestros días,
y no hemos alcanzado los años de nuestros antepasados.^
footnote:[Genesis 47:9]
En ese estado, la misericordiosa bondad me condujo a la Roca que es más alta que yo,
y mis ojos vieron que nosotros nos preocupamos por
cosas que no merecen la atención de la mente redimida,
y que si yo, o mis amigos con quienes me sentaba,
fuéramos llamados a dejar todo lo que está debajo del sol,
todas esas ansiedades desconcertantes se desvanecerían como un átomo en el torbellino,
y no tendrían ningún peso.
Entonces, sólo nos lamentaríamos de no haber mirado sobre esas momentáneas aflicciones,
y fijado nuestra confianza en el Brazo invisible, en el invencible poder del Omnipotente.
¡Pero, oh, cuán atraída es la parte natural por los objetos visibles!
Mientras que lo que es nacido de arriba, sufre por no aferrarnos a las cosas invisibles.

En esa reunión deseé ser favorecida con una extraordinaria visitación,
por medio de la cual pudiera estar dispuesta a rendirme
a cualquiera de las demandas del Señor,
habiendo tenido por mucho tiempo un gran temor sobre mi
espíritu con respecto a orar en las asambleas públicas.
¡Oh, eso quebrantaba la parte de la criatura en mí y me dejaba en el polvo!
Yo estaba dispuesta a respirar mentalmente al Señor durante toda la reunión,
pero cuando debía caer sobre mis rodillas para orar vocalmente, ¡oh,
los razonamientos que experimentaba!--que tal vez
la copa de favor no estaba suficientemente llena;
o que no me había acercado a Su trono como debía;
o que no estaba suficientemente revestida con el manto de alabanza;
o que el deseo ferviente por el bien de mis amigos no había llegado a su plenitud;
o que no tenía suficiente del Espíritu puro de Dios morando en mí,
que me permitiera mantenerme cerca de Su precioso, guiador y todo salvador poder,
como para ser preservada de ofrecer una palabra en
oración de la que Él no había sido el autor y requirente.

Aunque este es un tiempo de penuria,
y parezca una debilucha que acaba de entrar en el servicio,
aun así en varias ocasiones antes,
he sido convencida de invocar el nombre del Señor en público.
Pero después he tenido que someterme a un gran escrutinio de corazón,
para asegurarme de no haber cometido la menor desviación,
o haberme salido de la preciosa vida mientras estaba ocupada en ese servicio;
de modo que ahora,
mi parte natural está lista a desfallecer ante la
aparición y acercamiento de la intercesión pública.
¡Qué el Señor me ayude!
Tal vez, esta pequeña descripción sea, como "`el rosto que corresponde al rosto,
como en el agua`"^
footnote:[Proverbios 27:19]
para algunos que son muy concienzudos en cada movimiento,
especialmente en la oración vocal;
y en que siempre sea ofrecida en el entendimiento correcto, sazonada con gracia.

20 del mes Once, 1796.
Esta mañana he sentido el deseo de ser completamente lavada hasta quedar limpia,
"`tanto que ningún lavador en la tierra los puede hacer tan blancos.`"^
footnote:[Marcos 9:3]
Muchos están dispuestos a soportar los diversos bautismos espirituales,
siempre que estén seguros de que es Jesús quien los sumerge.
Pero tan inciertas y aparentemente casuales son las ocasiones de sus inmersiones,
que no creen que Él sea el autor de sus zambullidas,
o que sea Su santa mano la que está lavándolos y bañándolos por sus imperfecciones.
Pero si estos bautismos son soportados,
entonces el pecado es misericordiosamente eliminado;
¿y cómo pueden los que están muertos al pecado vivir aún en él?

28 del mes Tres, 1797.
Fui favorecida una vez más para asistir a nuestra Reunión Trimestral en Carlisle,
muy cerca del lugar de mi nacimiento y de la reunión a la que pertenecí
por muchos años. La reunión de ministros y ancianos fue un tiempo beneficioso.
Tuve evidencia de paz en mis pequeñas obras, y de hecho,
todas las reuniones fueron más o menos respaldadas con la reconfortante
presencia del rey de Sion en el corazón. Sentí que me estaba despidiendo,
y que estaba siendo ayudada a ser fiel, de modo que a mi regreso,
mi copa rebosó por muchas millas como si hubiera sido ungida
con el aceite de alegría. Grande era mi paz;
era un anticipo tan completo del gozo celestial, como no lo había experimentado antes,
excepto cuando abrí mi boca por primera vez en testimonio del Señor.
No parecía haber nada entre mi alma y su bendito Redentor.
En ese momento mi gozo era tan completo que anhelaba ser disuelta,
al no sentir nada más que pureza y santidad a todo mi alrededor.
O al menos,
tenía la sensación de plena aceptación del Padre en mis esfuerzos por obedecer.

En Carlisle, sentí la obligación de suplicar delante de Dios, en favor del pueblo.
Sentí amor por ellos,
y algunos de los ancianos y ministros se sintieron cercanos a mi vida interior.
En realidad, nunca antes había encontrado más apertura para suplicar con ellos,
que en la selecta reunión para ministros y ancianos, y sentí gran paz al hacerlo.
En el momento de la súplica, que fue al final de la última reunión,
creí sentir acceso abierto al Todopoderoso; de lo contrario,
no me habría atrevido a invocar con mi boca Su siempre bendito y digno nombre.
Durante ese terrible y solemne tiempo (porque así fue para mí),
me sostuve sobre una rodilla, ya que la otra no tenía fuerza,
lo cual me impidió continuar intercediendo tanto tiempo
como podría haberme inclinado para mi sólido consuelo.
Pero el Todopoderoso,
quien acepta el "`Abba Padre,`" oyó mi pequeña ofrenda y creo que mi esfuerzo fue aceptado.
Y si sólo hubiera doblado mis rodillas e invocado Su siempre digno nombre,
al ser Él el autor de mi súplica, a cambio de esta humilde dedicación,
habría dado la respuesta de paz.
¡Bendito sea el nombre del Señor para siempre!

Mes Cuatro, 1800.
Últimamente he estado confinada por una indisposición corporal,
durante la primera parte de la cual mi enfermedad fue extrema.
Me parecía que avanzaba rápidamente hacia la tumba,
aunque mi primera impresión Divina fue que yo no moriría en ese momento.
Pero como recientemente supe del caso de una ministra (con la que yo había viajado),
cuya muerte le fue completamente escondida, eso a veces me hacía estar insegura.

Tuve muchas enfermedades corporales, pero no mucho conflicto mental.
Me mantuve quieta y callada, lo que no era mi naturaleza, sino, ciertamente,
la misericordia de Dios.
¡Qué Su alabanza esté grabada en mi corazón mientras viva!
Fui favorecida con una fija, firme y consoladora esperanza de que si moría, me iría bien.
No deseo más evidencia cuando realmente entregue mi vida;
porque me pareció que los brazos de mi querido Redentor me envolvían con mucha seguridad,
de manera tal,
que el maligno (por el que yo a menudo había estado
angustiada en el lecho de enferma) no me pudo tocar,
ni tener ningún poder sobre mí.

Primer-día, 10 del mes Cinco, 1801.
Estando en la reunión en Whitehaven tuve una preciosa revelación,
por la que estuve a punto de levantarme.
Pero soy muy parecida al hombre enfermo del estanque de Betesda,
esperando el movimiento de las aguas, y mientras me estoy preparando, otro se adelanta.
Así fue este día, y aunque el individuo no dijo más que unas pocas palabras,
y no las escuché claramente, dejaron una angustia y tristeza de espíritu indecible,
de modo que el resto del día la hija de Judá, "`fue pisoteada como en un lagar.`"^
footnote:[Lamentaciones 1:15]

Mes Nueve, 1801.
Como en mí ha habido un ejemplo notable de la misericordia y poder de Dios--Su misericordia
al perdonar y Su poder al sostenerme--no puedo menos que alabarlo aquí y eternamente.
Y quienquiera que lea esto, humíllese en el polvo delante de Él;
porque Él es "`majestuoso en santidad, temible en las alabanzas, haciendo maravillas.`"^
footnote:[Éxodo 15:11 LBLA]

En la última parte de este año he tenido un tiempo de confinamiento por enfermedad,
y en esta temporada de debilidad,
no he sido tan favorecida con la evidencia de la
consideración Divina que sostiene el alma,
como en ocasiones anteriores.
Es posible que me haya consolado demasiado pensando en la abundancia de favores
que me fueron misericordiosamente concedidos en una enfermedad previa,
al no dudar de que si era probada de manera similar, yo sería igualmente sostenida;
y por lo tanto, corría el peligro de ser como Gedeón,
quien después de su gran logro hizo un Efod,
y al idolatrarlo se convirtió en una trampa para él.

30 del mes Seis, 1802.
Estuve en nuestra reunión de la semana, y fui favorecida con un silencio solemne,
similar al del cielo donde los ángeles y arcángeles adoran en profundo silencio.
¡Oh, vi en las alegrías de este, un lugar donde el dolor no puede llegar,
ni ninguno de los habitantes tiene alguna aflicción! Ese día fui favorecida
con el grado más alto de participación de la bondad Divina,
que posiblemente haya experimentado alguna vez.
El pan celestial fue entregado a mi alma en una porción nada escasa, con la palabra:
"`Toma, come, este es Mi cuerpo.`"^
footnote:[Mateo 26:26]

Hacia finales del año pasado (1801),
tuve la inquietud de que debía visitar algunos de los condados del sur o del sureste.
Me pareció que se había presentado con considerable claridad.
Me esforcé por mantenerme lo más cerca posible del Bien, y cuando estaba despierta,
rara vez no estaba consciente de ese Divino requerimiento.
El final del mes Quinto de 1802, me pareció el tiempo correcto para moverme.
No me tambaleé ante mi propio estado de debilidad
(porque yo estaba verdaderamente rendida a ir),
ni por la extrema debilidad de mi única hija sobreviviente;
de modo que parecía la prueba de Abraham,
al extender su mano para ofrecer a su único hijo.

Renuncié totalmente a mis pobres nietos, quienes, en realidad, eran huérfanos,
no permitiéndole a la parte afectiva tener dominio.
Rendí mi propia vida, las de ellos y todo lo que tenía en las manos del Todopoderoso,
sin atreverme a retroceder un ápice,
y ni siquiera desear que el servicio no fuera requerido
de mí. No me atreví a discutir la voz,
más de lo que hizo Abraham cuando fue llamado a ir a la tierra de Moriah.
Tal vez mi naturaleza retrocedió, como habría retrocedido la de él,
si no hubiera tenido la esperanza de: "`Dios se proveerá de cordero para el holocausto,
hijo mío.`"^
footnote:[Genesis 22:8]
Que los incrédulos den un paso al frente y cuestionen estas y otras sagradas verdades;
¡no importa!
Su incredulidad perecerá con ellos y dejará de propagarse cuando ya no existan.

Pero cuando llegó el momento en que debía preparar el viaje,
la perspectiva de viajar se cerró completamente y fui plenamente liberada de ir.
Me incliné con humildad y acepté mi liberación,
sintiendo esta advertencia--la de mantener mi vista hacia el gran Líder,
y no reincorporarme apresuradamente a mis asuntos familiares;
sino estar quieta y esperar,
sin alegrarme por mi liberación. Desde entonces he seguido sintiéndome libre.

12 del mes Cuatro, 1803.
Esta mañana antes de levantarme,
reflexionaba en mi mente como muchos de nuestra Sociedad son ricos y plenos,
por lo que se ve por su manera de vida y vestimenta.
Y que aunque su ropa es sencilla, es costosa y sus trajes son muchos.
Entonces me volví a mi propio estado bajo, sin lamentar que fuera así;
pues vi que es conveniente que un pueblo redimido sea ejemplar en el comer,
beber y vestir.
Durante esas consideraciones mi mente quedó satisfecha por esta palabra:
"`Te vestiré de salvación y coronaré tu fin con paz.`"
¿Podría pedir más para mí? ¡Ciertamente no!
Al ser favorecida y estar quebrantada bajo esto,
sintiéndome muy cerca del trono de la gracia,
se me permitió (en humildad) pedir que mi hija tuviera un lugar en el reino de los cielos,
y me acompañara en espíritu en el lugar que se considerara
adecuado que yo heredara cuando fuera desvestida de la mortalidad.
Después de esto oré por mis nietos.

23 del mes Doce, 1804.
En nuestra reunión del Primer-día, experimenté una especie de cielo abierto,
para mi propia satisfacción, y espero que para la de los demás. En efecto,
la Verdad se levantó en dominio y el poder opositor se hundió en la insignificancia.
Tales casos han sido raros en mí. Al dejar la reunión,
me fue dado un sentido de aceptación,
sintiendo de manera palpable la expresión "`bien hecho`" en mi propio caso,
junto con una secreta esperanza de que si continuaba dirigiendo mi rumbo cuidadosamente,
manteniendo mi vista en mi guía,
entregándole a la gente en sencillez y piadosa sinceridad lo que era inmediatamente dado,
siguiendo el hilo de mi testimonio en el poder, y dependiendo enteramente del Señor,
Él sería para mí boca y sabiduría, lengua y expresión. Así,
por un tiempo quedó aplastado Satanás bajo el pie.

7 del mes Cuatro, 1805.
Este día he experimentado un profundo bautismo del alma.
En realidad, pensé que aceleraría mi partida.
¡Oh, misericordioso Señor, mis tiempos están en Tus manos!
Tú sabes lo que puedo soportar.
Aligera mi carga, te ruego, o aumenta mi fuerza,
porque estoy siendo probada hasta la vida misma--"`crucificada juntamente con Cristo,
y ya no vivo yo, mas vive Cristo en mí.`"^
footnote:[Gálatas 2:20]
¡Oh, concédeme paciencia para soportar estos tiempos de sufrimiento!
Ciertamente Te preocupas de que yo sirva sola aquí.

A finales de 1805, o principios de 1806,
tuve una enfermedad por la que estuve confinada durante un tiempo.
Y una noche mientras estaba en la cama, entre las nueve y las diez,
en un estado de ánimo sólido y pesado, respirando hacia la Fuente de todo bien,
vi con mi ojo espiritual (tan claramente como mi ojo externo nunca ha visto ningún objeto)
que descendía el Anciano de Días. Su terrible majestad me envolvió como en una nube,
y envalentonada por Su inmerecida misericordia,
le pedí un lugar en Su glorioso reino cuando fuera despojada de mi vestidura mortal.
¡Escribo con un miedo terrible!
Pensé que se me había concedido,
y que se me permitía proseguir si tenía algo más.
Entonces imploré el mismo favor para mi única hija.
Pensé que también se me había concedido.
Y luego levanté mis ojos y mi corazón,
y al extenderse e inclinarse mi alma en buena voluntad hacia todos,
mentalmente derramé mi alma diciendo: "`¡Oh, Señor, la maldad del hombre es grande!`"
Y la respuesta que recibí fue:
"`Mi misericordia en más grande;`" y se cerró la visión. Pero, oh,
la plácida calma que dejó.

Han pasado casi quince meses desde que ocurrió esta muestra de la misericordia de Dios,
y no la he registrado hasta este momento,
para que nadie piense de mí por encima de lo que soy,
o para que ante el descubrimiento de tan ilimitada misericordia,
ningún pecador presuma continuar en su maldad,
con la esperanza de que Dios le muestre misericordia al final.
Pero en este momento me ha sido revelado otra vez;
y después de haber experimentado muchos profundos bautismos,
estoy despojada de toda gloria excepto en la cruz,
no teniendo otro deseo sino que estas líneas prediquen cuando yo ya no esté,
y animen a algún pobre pecador a levantar su cabeza con esperanza en lo que he escrito.

1806+++.+++ He envejecido,
y se anuncia que mis años declinantes no van a estar exentos de pruebas; en efecto,
realmente se incrementan.
Mi única hija está aquejada por un cáncer en su pecho.
El dolor y la gravedad de la enfermedad son tales
que languidecemos sin esperanza de que se recupere.
Este tiempo es de aflicción, ciertamente,
ya que no tenemos otro consuelo más que la reconfortante esperanza
de que sus problemas terminarán con el fin de su vida.

3 del mes Doce, 1806.
En nuestra reunión de entre semana,
estuve ocupada en exponer la necesidad de no sólo recibir la Semilla del reino,
sino que con toda prontitud, permitir Su crecimiento;
porque la obra de la Verdad en el corazón del hombre es descrita
por nuestra Gran Maestro como progresiva--"`primero hierba,
luego espiga, después grano lleno en la espiga.`"^
footnote:[Marcos 4:28]
Tuve paz al regresar a mi casa, y se me presentó esta palabra: "`Desde que naciste,
Mi amor ha estado contigo.`"
Esto me conmovió. Ojalá yo sea digna de tal favor.

14 del mes Tres, 1807.
Viendo retrospectivamente la senda que se me asignó a través de este valle de lágrimas,
y los pequeños relatos que he hecho de esta,
he pensado que a otros les podría parecer que he sido más herida
que mis contemporáneos en mis tempranos y profundos refinamientos;
o que desde entonces, al ser inusualmente despojada de mis amadas relaciones externas,
el árbol ha sido completamente pelado.
¡Qué ninguno de los viajeros hacia Sion sea desanimado por esto!
Porque, para alabanza de mi Padre celestial y de las riquezas de Su gracia,
recuerden que se me ha proporcionado la fuerza suficiente para cada día,
o de lo contrario yo nunca habría podido continuar hasta este momento.

Mi hija mayor y la última, ya está libre de todas sus pruebas, y un Dios misericordioso,
que nunca falla en el tiempo de necesidad,
visitó y sostuvo mi mente de manera maravillosa.
En el momento de su entierro, mientras estaba sentada en la reunión junto a su ataúd,
¡oh, la indescriptible paz que sentí,
con la consoladora seguridad de que todas sus lágrimas habían sido enjugadas para siempre!
En verdad, ellas habían fluido como ríos bajo profundos ejercicios religiosos.
En ese momento,
la misericordia de nuestro Padre celestial era tal hacia mí (una pobre e indigna criatura),
que parecía como si su espíritu purificado descendiera y descansara
sobre los restos de ella durante la reunión. ¡Oh,
cómo puede adorarlo suficientemente!

4 del mes Quinto, 1807.
El día cuatro estuve en la reunión. Algunos de nuestros Amigos habían partido para Londres.
Fue para mí un tiempo solemne, porque estaba muy ocupada en mis respiraciones mentales;
y el Espíritu estaba ayudándome en mi debilidad a orar en el interior.
Una gran porción del pan celestial me fue dado sin mucha lucha,
y sin tener que ofrecerlo a los demás. Y aunque los enemigos de nuestra alma son numerosos,
se reveló en mí una palabra viva: "`El Señor peleará por ti y tú estarás tranquila.`"^
footnote:[Éxodo 14:14]
Esto fue aplicado a mí,
ya que no tuve comisión de Él para divulgarlo a los
demás. Algo como las arras del Espíritu de adopción,
o santa promesa, acompañaron mi mente, y concluyó con: "`Señor,
Tú eres bueno con nosotros, te alabaremos; exaltaremos Tu nombre.`"
Tuve un fuerte consuelo en el único sabio Dios--Omnipotente, Omnisciente y Omnipresente.
Siempre estamos ante Su vista, desnudos y despojados delante de Él. ¡Oh,
quién se atrevería a hacer el mal!

13 del mes Doce, 1807.
Toda mi familia se ha ido a la reunión y yo me he quedado en casa por indisposición.
Pero debo reconocer la bondad del misericordioso Dios hacia mí,
que ha estado cerca en este tiempo de confinamiento, al permitirme derramar mi alma,
e incluso (a veces he pensado) de reclinarme en Su propio pecho.
Y la palabra consoladora ha sido: "`No temas, Yo soy el primero y el último.`"^
footnote:[Apocalipsis 1:17]

4 del mes Primero, 1808.
Un rico favor se me extendió esta mañana, pobre gusano,
y dado en estas consoladoras palabras: "`Mi amor y cuidado, sí, cuidado protector,
siempre han sido hacia ti,
y Yo nunca te dejará ni te desampararé. Aunque en días pasado se
le haya permitido a Satanás rugir y disparar sus malignas flechas,
ahora estará quieto.`"

Yo ansiaba la renovación de la visión Divina con la que
había sido favorecida en una enfermedad anterior,
pero la infinita Sabiduría consideró oportuno retener cualquier otra cosa de esa naturaleza.
¡Adoro y bendigo Su santo nombre! ¡Le pido a Dios, con todo mi corazón,
que sea así conmigo en mis últimos momentos; y humildemente confío que así será,
si mantengo mi lugar hasta el final,
porque ciertamente Él ha sido un Dios misericordioso para conmigo! ¡Qué los miembros
de esta reunión busquen más y más ese poder que se ha interpuesto tan notablemente
para la liberación de mi alma! ¡Qué ninguno de ellos se pierda!
Pues realmente se han hecho grandes esfuerzos con esta parte del viñedo del Señor.

7 del mes Segundo, 1808.
Durante muchos meses mi mente ha sido preservada en estado de tranquilidad,
a pesar de las cosas en el exterior que a veces me afligían.
No sentía ninguna inclinación al mal en mí,
ni ninguna tentación de este;
y el misericordioso Padre no estaba lejos de mí. Pero empecé a dudar de mi condición,
para no atribuirle esta serenidad (que podría llegar a ser continua)
a un crecimiento en la Verdad y al favor de mi Dios,
antes de haberla alcanzado realmente.
Por tanto, casi deseaba volver a sentir mi acostumbrada pobreza de espíritu,
junto con Su escarmiento, creyéndome muy lejos de la perfección.

Pero ahora,
le ha parecido a Él oportuno cambiar el tiempo favorable a uno más purificante y exigente,
retirando a menudo Su favor, de modo que yo no pareciera ni '`traída sobre el costado,
ni acariciada sobre la rodilla.`'^
footnote:[Isaías 66:12]
Lo soportaré, porque, ¡oh, temo estar '`reposada en Sion,`'^
footnote:[Amós 6:1]
o confiando en cualquier cosa que no sea lo verdaderamente sustancial,
que alimenta y nutre al alma para vida eterna!

7 del mes Quinto, 1810.
He llegado a los setenta y cinco años,
y al volver a leer lo que hace mucho tiempo se escribió
acerca de los tratos del Señor conmigo en mi estado infantil,
siento la renovación de ese antiguo poder que impresionaba mi mente mientras escribía;
por tanto, espero que no sean palabras que caigan al suelo,
porque son dichos fieles y verdaderos.
Lector, si cuando los lees, oyes un suave llamado: "`El Maestro está aquí y te llama,`"^
footnote:[Juan 11:28]
entonces levántate rápidamente,
como hizo María. Deja que los demás sospechen lo que quieran con respecto a tu prisa.
Estos son tiempos en los que no debemos "`saludar a nadie en el camino.`"^
footnote:[Lucas 10:4]

Hay muchas publicaciones en el mundo.
Algunas de ellas tienen tendencia a corromper la moral de quienes las leen.
Estas nunca se han cruzado en mi camino, ni me he atrevido a pasar mi tiempo leyéndolas.
Sin embargo, hay otros libros que son considerados más inocentes,
y como han sido introducidos en mi familia,
he creído conveniente ver la naturaleza de ellos,
y considerar qué inclinación podrían tener sobre
las mentes que parecían deleitarse en ellos.
Tengo esto para proponerlo a la seria consideración de todos,
especialmente a los jóvenes, o incluso, a los más avanzados en nuestra Sociedad,
a quienes estos libros les son placenteros.
A estos les digo: Lean las Escrituras y otros libros verdaderamente buenos,
observen el tenor de sus mentes mientras leen.
Sentirán cuáles de ellos acercan el alma a Dios--si
estas publicaciones a las que me he referido,
o las que han sido escritas por los verdaderos testigos
de la vida y muerte de nuestro Salvador.

En los registros escritos de Su vida,
percibiremos dónde han sido pisadas en profunda humildad las huellas del Maestro.
Veremos Su costado herido y la marca de los clavos, ante cuya vista,
parece sentirse una virtud viva.
Tales autores, debemos creer,
han estado con Jesús. La lectura de Sus sufrimientos en mi temprana juventud me conmovió,
como mencioné antes, y me unió a Su Espíritu puro.
¡Oh, qué toda la humanidad lo vea como yo lo veo ahora!
Cuán temerosos estarían de dar dinero (que podría
ser mejor empleado) por publicaciones inútiles.
Ni se atreverían a gastar su precioso tiempo en la lectura de tales cosas.

6 del mes Ocho, 1810.
Me ha sorprendido que cuanto más anciana me hago y más débil me siento,
más ensanchada estoy de mente,
y más iluminada con respecto a las frases de las Escrituras.
¡Oh, cómo se ilumina la Palabra (cuando viene) en mi mente,
y me da la habilidad de ver internamente más allá! Es obra
del Señor y verdaderamente maravillosa a mis ojos.
Señor,
¿qué soy yo para que sigas reconociéndome así y expandiendo mi corazón en la vejez,
cuando los guardianes de este frágil edificio tiemblan sobremanera?
Me siento tan humillada como para considerarme vil,
pobre e indigna de un lugar donde reside la Majestad de los cielos.
¡Oh, cuando esto mortal sea puesto en inmortalidad,
y cada semilla reciba su propio cuerpo,
el mío ciertamente será como el del orden más bajo de los ángeles!
Sembrado en debilidad, aunque sea levantado en poder.
Pero, cesa, alma mía, de husmear en los secretos de la eternidad!
Los lugares de habitación más bajos en la casa del Padre,
superarán con creces mis servicios.
¡Oh, Señor, mantente cerca al final del tiempo, es mi sincera oración!

14 del mes Once, 1810.
Hoy tuvimos un tiempo muy fortalecedor en nuestra reunión de entre semana en silencio.
Pensé que yo no dudaría nunca más estando bajo el cuidado del cielo,
la evidencia era tan fuerte y mi amor parecía tan perfecto hacia Dios,
que desechaba todo temor.
No le temía a la muerte, ni al infierno ni a la tumba.
Los ejércitos de los extranjeros, por el momento, habían sido enteramente puestos en fuga.
Mi fe era fuerte con respecto a mi propio bienestar, incluso,
tenía fe por aquellos que estaban reunidos conmigo.
De hecho, parecía que habíamos llegado a Sion, la ciudad del Dios vivo,
y que estábamos reunidos en espíritu con una innumerable compañía de ángeles.
Previo a este precioso tiempo,
yo había tenido grandes revelaciones de las cosas Divinas pertenecientes
a otra vida--cosas tan sagradas como para no entremeterse--que
me llevaron a pensar que pronto iba a morir.

En la reunión de entre semana vi, como desde el monte,
que los muchos momentos de prueba a los que a menudo he sido conducida en nuestras reuniones,
eran necesarios,
para que no me exaltara por las sublimes revelaciones con las que he sido favorecida.
Esto hizo por mí, lo que el aguijón en la carne hacía por Pablo,
y ahora parezco una de las más pequeñas,
y me veo a mí misma en una luz verdaderamente humilde.

23 del mes Siete, 1811.
Reunión mensual, Pardshaw Hall.
Estando en Underwood asistí a esta reunión y me pareció un tiempo muy favorable.
La gloria del Señor, según me pareció, llenaba la casa; y sentados en el propiciatorio,
cada uno parecía tener el misericordioso privilegio del perdón. Eso me
recordó cuando el apóstol Pablo había sido arrebatado al tercer cielo,
y había visto y oído lo que no era lícito que una criatura finita pronunciara;
ni yo tampoco me atreví a pronunciar, del lado de la misericordia,
lo que sentía entonces.
Pensé que si hubiera continuado así bajo la directa consciencia de la presencia de Dios,
no habría sentido hambre ni dolor.
Pero ese era un estado en el que no se podía continuar, y en mi regreso a casa,
la misericordiosa presencia se retiró. No digo que
un mensajero de Satanás hubiera sido enviado a abofetearme,
pero me hundí en dudas tan desgarradoras con respecto a mi propia salvación,
que me impidieron exaltarme por encima de toda medida,
debido a la abundante revelación que misericordiosamente me había sido concedida.
No vi que hubiera errado en mis comunicaciones a los Amigos reunidos,
porque no había encendido mi propio fuego, ni me había calentado con las teas de este,
como para no tener que yacer en tormento.^
footnote:[Isaías 50:11]

¡Oh, Señor, te ruego que me mantengas en Tu paciencia,
y que Tu poder refinador no deje nada que esté mal en mí, sin someter!
Tú, oh, Señor, conoces por lo que he pasado en mi juventud, y todo el tiempo.
Tu mano ha sido pesada sobre mí. Tú, oh, Señor,
a menudo me has hecho ver que no me imputas ninguna iniquidad,
sino que me has dado un sentido de plena aceptación para Contigo.
Por tanto: "`¿Por qué te abates, alma mía,
y por qué te turbas dentro de mí? Espera en Dios; porque aún he de alabarle.`"^
footnote:[Salmo 42:11; 43:5]

Al escribir estas observaciones, siento que el bien se levanta en mí,
lo cual venda mi quebrantado corazón. Porque aunque
ciertamente tengo pruebas pesadas en el exterior,
ellas no han tenido participación en mi presente bautismo.
Fue, porque "`mi Amado se había ido, ya había pasado.`"^
footnote:[Cantares 5:6]
Una época de esta naturaleza no me habría consternado tanto,
si no hubiera estado tanto tiempo en el ministerio.
Pensé que el Gran Maestro me había puesto a prueba en cuanto a la auto exaltación,
y había mostrado que yo no me atrevería a decir:
"`El Señor dice,`" cuando Él no había hablado; de modo que,
realmente esperaba haber sido establecida sobre la Roca inamovible.
Pero descubro, que los que piensan que están firmes deben tener cuidado de no caer.
Tampoco debemos recurrir a esos sublimes descubrimientos
que la luz Divina nos ha manifestado previamente.
Sino más bien, después de experimentar un gran favor en la visión espiritual,
debemos permitir que todo regrese a la Fuente de donde surgió. ¡Ah, entonces,
cuán vacíos y despojados estamos!
Porque las vasijas que han sido usadas, deben ser lavadas.
¡Y cuán inseguro es para nosotros,
alimentarnos de cualquier bien que hayamos sido capaces de hacer anteriormente!
Nosotros sabemos, por experiencia, que esto es verdad,
que no somos salvos por obras de justicia que hayamos hecho,
sino por Su misericordia--y que esto es por el lavamiento
de la regeneración y renovación del Espíritu Santo.

29 del mes Primero, 1812.
Cuarto-día. Una reunión preciosa para mí; en efecto,
me pareció que la solemnidad se esparcía sobre todos.
¡Oh, el silencio puro que sentí,
como si Emanuel hubiera extendido Sus alas y nos hubiera cubierto!
Aquella sublime y exaltada visión del profeta fue
traída claramente a la vista de mi mente,
cuando él vio "`al Señor sentado sobre un trono alto y sublime,
y sus faldas llenaban el templo.
Por encima de él había serafines; cada uno tenía seis alas; con dos cubrían sus rostros,
con dos cubrían sus pies, y con dos volaban.
Y el uno al otro daba voces, diciendo: Santo, santo, santo, Jehová de los ejércitos;
toda la tierra está llena de su gloria.
Y los quiciales de las puertas se estremecieron con la voz del que clamaba,
y la casa se llenó de humo.`"^
footnote:[Isaías 6:1-4]

Pregunté si debía divulgarlo a los presentes, y la respuesta que recibí fue:
"`Es un favor y un alimento para ti, y si le das a otros tu propia porción,
pronto estarás escasa y flaca.`"
Di las gracias y reconocí con agradecimiento el favor concedido,
y ahora resuelvo aferrarme a la evidencia confirmatoria que tuve entonces.
Sin embargo, a veces me asalta el temor, no sea que la pierda de nuevo y dude.

5 del mes Cuatro, 1812.
Después de un tiempo de enfermedad,
esta mañana se me entregó misericordiosamente como Divino consuelo:
"`Tú estás en el hueco de Mi mano;`" y otra vez: "`El Señor es mi pastor,
nada me faltará.`" ¡Oh, Señor, qué indecible favor es este,
cuando la debilidad de mi cuerpo a veces es tanta como la naturaleza puede soportar!
He pasado hasta ahora por el desierto de este mundo en tan gran peligro,
tan estrechamente probada, y tan cerca de desmayar bajo mis pruebas,
como tal vez ningún pobre mortal lo haya hecho alguna vez.
¡Qué indescriptible favor,
cuando acercándome ahora a los confines de la estrecha y silenciosa tumba,
una criatura tan indigna sea así reconocida! ¡Oh, misericordioso Padre,
continúa con Tu cuidado preservador y protector hacia
mí hasta los últimos momentos de mi vida,
y yo elogiaré y alabaré Tu nombre mientras esté aquí y por siempre!
Amén.

Mes Seis, 1812.
Recuperada de una reciente enfermedad,
me sentí inclinada a revisar los papeles que había escrito bajo un sentido religioso,
y al repasar esa extraordinaria visión un temor impresionó mi mente,
no fuera que alguien en adelante pensara que yo había
sobrepasado los límites de una criatura finita.
Considerando esto se me ocurrió dejar que recordaran mis profundos ejercicios,
dura servidumbre y amarga esclavitud en el horno de hierro,
en una tierra de una oscuridad tan espesa que se podía sentir.
Estaba tan estropeada que me convertí en una maravilla para mis contemporáneos.
Ahora bien,
si después de esto el bondadoso Dios tuvo a bien inclinar los cielos y bajar
a tocar mi corazón para que fuera conmovido--siendo Él Omnisciente--¿quién,
después de tan grande favor,
estimaría livianamente a la Roca de su salvación? Aunque Él es
el Alto y Santo que mora en la luz y habita en la eternidad,
se nos asegura que Él se complace en revivir los espíritus de Su pobres,
contritos y humildes siervos, que tiemblan ante Su palabra.

Nuestro bendito Señor y Salvador Jesucristo,
que es nuestro Intercesor y Mediador entre Dios y el hombre,
cuando se le preguntó el porqué Él se manifestaría a Sus escogidos y no al mundo,
selló la promesa así: "`El que me ama, mi palabra guardará; y mi Padre le amará,
y vendremos a él, y haremos morada con él.`"^
footnote:[Juan 14:23]
Esto no habla de "`un caminante que se retira para pasar la noche,`"^
footnote:[Jeremías 14:8]
y luego se va; sino de Cristo instalando Su morada con ellos como un bendito invitado,
como "`un maestro`" en casa, "`que nunca más será quitado.`"^
footnote:[Isaías 30:20]

Estas revelaciones en mi mente me confirman una comunión Divina; y ahora lo dejo.
Y si se considera correcto suprimir completamente alguna parte de todo lo que he escrito,
la voluntad de los Amigos sea hecha en la Verdad.
Porque, ¡temo la presunción!, sabiendo que el árbol alto debe ser abatido,
y el bajo exaltado; que el árbol verde debe ser secado, y el seco debe hacerse florecer.

14 del mes Tres, 1813.
Un profundo reconocimiento de la misericordia de Dios.
Mientras estaba en la cama esta mañana,
bajo una punzante aflicción de mente por causa del alejamiento de mi nieto de la Verdad;
aunque en la más profunda aflicción, se le permitió a mi espíritu ascender,
pensé que hasta el trono del Todopoderoso.
Ahí derramé mi alma por mi cuenta y por la de él, y la bondad condescendiente concedió,
en la abundante misericordia, develar Su bondadoso semblante y hacerme saber,
que yo no debía discutir las seguridades que Él me había dado de Su favor,
y que si después de todas las evidencias que Él me había dado de Su cuidado protector,
yo desechaba mi confianza en Él, sería peor que un infiel.
Entonces una pequeña esperanza revivió de que el
pobre descarriado joven aún sería visitado con misericordia.
Esta perspectiva, aunque sólo tendía a vendar mi corazón roto,
o sanar mi espíritu herido, la acepté con agradecimiento de mi Dios.

¡Oh, bondadoso Padre, en Tu inagotable bondad,
guarda este pequeño rebaño (los miembros de esta reunión,
entre quienes he trabajado a menudo) cuando yo ya
no esté! Que nunca se conviertan en una desolación,
en un caldo de cultivo de ortigas,
sino que continúen creciendo en la nobleza de la Verdad.
Queridos Amigos,
nada servirá sino mantenerse cerca de Dios y morar siempre como en Su presencia.
No hagan nada ante Su vista que teman que algún mortal vea.
Mantengan un corazón puro y manos limpias, y su final será paz.
Siento este amor por la Reunión Mensual--pues sus miembros son muy queridos para mí.

2 del mes Seis, 1813.
En el regreso a casa de nuestra reunión de entre semana,
en la que yo había sido fiel según la visión y percepción que se me habían dado,
revivió este anuncio: "`El Señor ve como tiembla tu cabeza y se sacuden tus extremidades,
y en Su tiempo, te hará libre.`"
A partir de esto, brotó una bendita esperanza en mí, de que aunque sembrada en debilidad,
yo sería levantada en poder.
¡Oh, bendito sea Su santo Nombre! --porque Él alimenta al hambriento con cosas buenas,
pero al rico y lleno lo despide vacío.

Nuestra Reunión Mensual en Whitehaven, en el mes Ocho de 1813,
fue para mí un tiempo de consuelo.
No se oía nada más que la voz de acción de gracias y alabanza.
El gran adversario fue totalmente dominado;
no apareció ni una sola nube para eclipsar la gloria
del día o atenuar la belleza de Sion.

21 del mes Diez, 1813.
He tenido este día, en la reunión semanal en Whitehaven,
la más indiscutible evidencia de la sombra del amor y misericordia Divinos,
que recuerde haber experimentado alguna vez.
Ciertamente se podría decir, que el ala del Todopoderoso estaba sobre nosotros.
Fue ofrecida Su reconciliación, y del lado de la misericordia,
vi más de lo que tengo libertad de escribir o hablar.
¡Oh, mis queridos Amigos que pertenecen a esta reunión,
especialmente a los que estaban en la reunión ese día,
apreciemos la bondad del Señor para con nuestras almas!
Mi amor era tal por ustedes,
que me resultaba casi insoportable que alguno de ustedes quedara destituido
del descanso celestial que yo veía que estaba destinado para nosotros--mucho,
mucho más allá de la concepción de cualquier criatura finita.

31 del mes Diez, 1813.
¡Oh, las consoladoras visiones que he experimentado durante mi último confinamiento!
Un rico tributo de acción de gracias y alabanza se debe a mi bendito Señor y Maestro,
Jesucristo, por el sentido con el que le ha placido favorecerme,
de que Él ha oído mis oraciones por mi pobre nieto.
Porque un poco antes de su muerte, el Espíritu de intercesión fue derramado sobre mí,
y mis oraciones fueron fuertes por él.

Aunque tiemblo mucho y mi mano es muy inestable, con todo,
si es correcto que deje para la posteridad la memorable
misericordia del Todopoderoso conmigo (un pobre gusano),
podré hacerla legible.
El 13 del mes Doce de 1813, sentada en la noche junto al fuego,
con un grupo a mi alrededor ocupado en una conversación,
sentí una fuerte atracción hacia el cielo que me alegró. Y un bondadoso
Dios pareció complacerse en inclinar Sus cielos y descender,
dirigiéndome a que desechara toda duda con respecto a mi propia partida;
porque Él me tomaría en Su misericordia y me sostendría
a través de lo que me pudiera suceder.
Y mi encargo fue nunca más dudar de mi descanso eterno.
Y con respecto a mi nieto, se me dijo que no dudara más,
porque se le había concedido arrepentimiento en el último momento.^
footnote:[Este pobre joven estaba confinado en una
habitación en el hospital militar de Chelsea,
con muchos otros en el mismo salón, lo cual lamentaba mucho,
porque no podía alcanzar ese estado de ánimo tranquilo que tanto deseaba.
Se dio cuenta de sus errores,
y expresó la angustia que sentía por el malestar que había causado a su abuela,
temiendo que se acortaran los días de ella; y estaba muy ansioso de leer su Biblia.
Pronunció algunas expresiones sorprendentes cerca de su final,
que no se recuerdan con claridad,
pero el día y la hora de su muerte se correspondieron con las impresiones
reconfortantes que su abuela había recibido con respecto a él.]
El Espíritu de intercesión fue derramado sobre mí con tal energía,
que parecía rasgar los mismos cielos.
¡Oh, alma mía, no olvides este momento,
ni dejes de exaltar a un misericordioso Dios que perdona a los transgresores!
En este caso, la misericordia ha cubierto cada milímetro del tribunal.

La presencia del Todopoderoso era tan plena y confirmadora,
que me pareció que era todo lo que mi frágil tabernáculo podía soportar y vivir.
Experimenté entonces, que ninguna carne podía verlo en Su majestad y vivir.
Aunque en una ocasión anterior yo había estado en una situación algo similar,
no tenía el sentido que se me había dado entonces,
de que si el favor Divino se incrementaba, mi cuerpo no podría retener mi espíritu.
Ahora, desisto de exponerme más,
sintiéndome superada por la presente extensión de la gracia.
¡Oh, misericordioso Dios!

16 del mes Primero, 1814.
Este día, después de que los Amigos se habían ido a la reunión, estaba muy baja en mente;
cuando las palabras del profeta vinieron a mí muy vívidamente diciendo,
que el Señor haría "`que el lugar seco se convirtiera en estanque.`"^
footnote:[Isaías 35:7]
Y después de sentarme en esta desconsolada condición, fui consolada con:
"`Estoy cerca de ti, aunque no lo sepas.`"

14 del mes Ocho, 1814.
¡Oh, la misericordia de un bondadoso Dios hacia mí,
en mi vejez y gran debilidad corporal,
quien me ha dado experimentar esta mañana que "`el justo vive por la fe.`"^
footnote:[Romanos 1:17; Gálatas 3:11; Hebreos 10:38]
Si no fuera por esta preciosa fe, yo estaría al borde de la caída, casi en cada momento.
¡Oh, bendito sea Tu santo nombre para siempre!

19 del mes Nueve, 1814.
Esta mañana otra vez tuve la más fuerte y consoladora evidencia del favor Divino,
que mi pobre estado podía soportar--haciéndome saber que a medida que decrecía mi fuerza,
se incrementaba Su vigilante cuidado sobre mí. Y aunque
ha considerado adecuado casi privarme de mi oído externo,
Él ha incrementado el interno de manera tan sorprendente,
que a menudo me parece que caigo delante de Él en
asombro--al estar mi mente tan expandida y ampliada,
que en la medida que lo natural se abate, lo espiritual se incrementa,
y mi querido Redentor me permite, por momentos, reposar como en Su seno.

[.asterism]
'''

[.emphasized]
Después de esto, Jane Pearson no escribió más para el escrutinio público.
Sin embargo, durante muchos meses, a pesar de su gran debilidad y dolor corporal,
continuó conversando con sus amigos,
más frecuentemente con respecto a la bondad del Todopoderoso.
No muchas semanas antes de su fallecimiento, cuando un Amigo se alejó de ella,
parecía afectada y dijo: "`Aunque mis lágrimas caen, no me he quedado sin consuelo.
No; no hemos seguido fábulas astutamente concebidas.
Creo que lo que siento ahora podría convencer al mundo entero.
¡Oh, es maravilloso! ¡Es maravilloso!`"
A los que estaban con ella en el momento de su muerte,
les pareció que el último esfuerzo de su piadosa vida había sido la oración;
pero no se pudieron oír con claridad las palabras.
Partió tranquilamente hacia las tres del 20 del mes Dos de 1816,
a la edad de ochenta y un años, y fue ministra de la Sociedad de Amigos,
alrededor de cuarenta y dos años.
